-   id: textlint
    name: textlint
    description: ''
    entry: textlint
    language: node
    'files': \.(md|mdown|markdown)$
    args: []
    require_serial: false
    additional_dependencies: ["textlint@7.2.1-alpha.342420c1"]
    minimum_pre_commit_version: '0'
